"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character
"""

add_newline = false

[username]
style_user = 'bg:cyan fg:bright-white'
style_root = 'bg:red fg:bright-white'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$ssh_symbol](bg:cyan fg:bright-white)[$hostname](bg:cyan fg:bright-white)'
trim_at = '.companyname.com'
disabled = false

[shell]
format = '[$indicator](cyan bold)'
fish_indicator = "F"
bash_indicator = "B"
zsh_indicator = "Z"
disabled = true

[directory]
style = 'bg:black fg:bright-white bold'
home_symbol = "~"
format=' [$path$read_only]($style)'

[character]
success_symbol = " [\\$](bright-white)"
error_symbol = " [\\$](red)"
vimcmd_symbol = " [\\$](bright-white)"

[git_branch]
format = "[ $branch]($style)"
style = 'bg:black fg:bright-white bold'

[git_status]
style = "bg:black"
format = "[ $ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style)"
conflicted = "[!](bg:black fg:bright-magenta)"
ahead = "[↑[${count}](bg:black fg:bold white)](bg:black fg:green)"
behind = "[↓[${count}](bg:black fg:bold white)](bg:black fg:red)"
diverged = "[↑[${ahead_count}](bg:black fg:regular white)↓[${behind_count}](bg:black fg:regular white)](bg:black fg:bright-magenta)"
untracked = "[?](bg:black fg:bright-yellow)"
stashed = "[≡](bg:black fg:white)"
modified = "[*](bg:black fg:yellow)"
staged = "[+[$count](bg:black fg:bold white)](bg:black fg:bright-cyan)"
renamed = "[»](bg:black bright-blue)"
deleted = "[x](bg:black red)"

[git_state]
format = ' [$state( $progress_current/$progress_total)]($style)'
style = "bg:black fg:bright-black"
