[config]

[templates]
# [templates.qutebrowser]
# input_path = "~/.config/noctalia/templates/qutebrowser/noctalia.py.tail"
# output_path = "~/.config/qutebrowser/noctalia.py"

# [templates.kitty]
# input_path = '~/.config/noctalia/templates/kitty/noctalia.conf.tail'
# output_path ='~/.config/kitty/themes/noctalia.conf'
# post_hook = "kitty +kitten themes --reload-in=all noctalia &"

[templates.gtk-folder]
input_path = '~/.config/noctalia/templates/gtk-folder/recoloricons.sh.tail'
output_path = '~/.cache/noctalia/recoloricons.sh'
post_hook = 'bash ~/.cache/noctalia/recoloricons.sh &'

[templates.wmenu-color]
input_path = '~/.config/noctalia/templates/wmenu/color.sh.tail'
output_path = '~/.config/wmenu/color.sh'

[templates.rmpc]
input_path = '~/.config/noctalia/templates/rmpc/noctalia.ron.tail'
output_path = '~/.config/rmpc/noctalia.ron'

[templates.tmux]
input_path = '~/.config/noctalia/templates/tmux/color.conf.tail'
output_path = '~/.config/tmux/color.conf'
post_hook = 'pgrep tmux && tmux source-file /home/harunato/.config/tmux/color.conf'

# [templates.btop]
# input_path = '~/.config/noctalia/templates/btop/noctalia.theme.tail'
# output_path = '~/.config/btop/themes/noctalia.theme'
# post_hook = 'pkill -USR2 btop || true'
#
# [templates.cava]
# input_path = '~/.config/noctalia/templates/noctalia.tail'
# output_path = '~/.config/cava/themes/noctalia'
# post_hook = 'pkill -USR1 cava'
#
# # not write
# [templates.dunst]
# input_path = '~/.config/noctalia/templates/dunst/dunstrc.tail'
# output_path = '~/.config/dunst/dunstrc'
# post_hook = 'dunstctl reload'
#
# [templates.gtk3]
# input_path = 'path/to/template'
# output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
#
# [templates.gtk4]
# input_path = 'path/to/template'
# output_path = '~/.config/gtk-4.0/colors.css'
#
# [templates.niri]
# input_path = 'path/to/templates/niri-colors.kdl'
# output_path = '~/.config/niri/colors.kdl'
# post_hook = 'niri msg action load-config-file'
# [templates.pywalfox]
# input_path = 'path/to/template'
# output_path = '~/.cache/wal/colors.json'
# post_hook = 'pywalfox update'
# [templates.qt5ct]
# input_path = 'path/to/template'
# output_path = '~/.config/qt5ct/colors/matugen.conf'
# [templates.qt6ct]
# input_path = 'path/to/template'
# output_path = '~/.config/qt6ct/colors/matugen.conf'
# [templates.yazi]
# input_path = 'path/to/template'
# output_path = '~/.config/yazi/theme.toml'
# [templates.kcolorscheme]
# input_path = 'path/to/template'
# output_path = '~/.local/share/color-schemes/noctalia.colors'
