[icon]
prepend_dirs = [
	{ name = "Templates", text = "" },
  { name = "Go", text = ""},
  { name = "Game", text = "" },
  { name = "dotfiles", text = "" },
  { name = "Record", text = "" },
  { name = "smb", text = "" },
  { name = "Mail", text = "" }
]

[flavor]
dark  = "matugen"
light = "matugen"
