# [flavor]
# dark  = "noctalia"
# light = "noctalia"

[icon]
prepend_dirs = [
	{ name = "Templates", text = "" },
  { name = "Go", text = ""},
  { name = "Game", text = "" },
  { name = "dotfiles", text = "" },
  { name = "Record", text = "" },
  { name = "smb", text = "" }
]

[flavor]
dark  = "noctalia"
light = "noctalia"
