#!/bin/bash

LOCKFILE="/tmp/mango-workspace.lock"
CACHE="$HOME/.cache/mango-workspace.log"

clean_up() {
    rm -f "$CACHE"
    killall mmsg
}

trap clean_up EXIT INT TERM

exec 200>"$LOCKFILE"
flock -n 200 || exit 1

COLORS="$HOME/.config/waybar/mango/colors.css"

get_color() {
    grep "@define-color $1 " "$COLORS" | awk '{print $3}' | tr -d ';'
}

PRIMARY=$(get_color primary)
ON_PRIMARY=$(get_color on_primary)
ON_SURFACE=$(get_color on_surface)

# render() {
#     mmsg get all-tags 2>/dev/null |
#     jq -r '
#         .all_tags[].tags[]
#         | "\(.index) \(.is_active) \(.client_count)"
#     ' |
#     awk \
#     -v primary="$PRIMARY" \
#     -v on_primary="$ON_PRIMARY" \
#     -v on_surface="$ON_SURFACE" '
#     BEGIN {
#         out = ""
#     }
#
#     {
#         name = $1
#         focused = ($2 == "true")
#         occupied = ($3 > 0)
#
#         if (focused && occupied) {
#             out = out \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" rise=\"4200\">▪</span>" \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" rise=\"-4200\">​</span>" \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" weight=\"bold\">" name " </span>"
#         }
#         else if (focused) {
#             out = out \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" rise=\"4200\"> </span>" \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" rise=\"-4200\">​</span>" \
#             "<span background=\"" primary \
#             "\" foreground=\"" on_primary \
#             "\" weight=\"bold\">" name " </span>"
#         }
#         else if (occupied) {
#             out = out \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" rise=\"4200\">▫</span>" \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" rise=\"-4200\">​</span>" \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" weight=\"bold\">" name " </span>"
#         }
#         else {
#             out = out \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" rise=\"4200\"> </span>" \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" rise=\"-4200\">​</span>" \
#             "<span background=\"" on_primary \
#             "\" foreground=\"" on_surface \
#             "\" weight=\"bold\">" name " </span>"
#         }
#     }
#
#     END {
#         print out
#     }'
# }

# normal font
render() {
    mmsg get all-tags 2>/dev/null |
    jq -r '
        .all_tags[].tags[]
        | "\(.index) \(.is_active) \(.client_count)"
    ' |
    awk \
    -v primary="$PRIMARY" \
    -v on_primary="$ON_PRIMARY" \
    -v on_surface="$ON_SURFACE" '
    BEGIN {
        out = ""
    }

    {
        name = $1
        focused = ($2 == "true")
        occupied = ($3 > 0)

        if (focused && occupied) {
            out = out \
            "<span background=\"" primary \
            "\" foreground=\"" on_primary \
            "\" rise=\"4000\" size=\"xx-large\">▪</span>" \
            "<span background=\"" primary \
            "\" foreground=\"" on_primary \
            "\" rise=\"-14000\">​</span>" \
            "<span background=\"" primary \
            "\" foreground=\"" on_primary \
            "\" weight=\"bold\">" name "  </span>"
        }
        else if (focused) {
            out = out \
            "<span foreground=\"" primary \
            "\" background=\"" primary \
            "\" rise=\"4000\" size=\"xx-large\">▪</span>" \
            "<span background=\"" primary \
            "\" foreground=\"" on_primary \
            "\" rise=\"-14000\">​</span>" \
            "<span background=\"" primary \
            "\" foreground=\"" on_primary \
            "\" weight=\"bold\">" name "  </span>"
        }
        else if (occupied) {
            out = out \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_surface \
            "\" rise=\"4000\" size=\"xx-large\">▫</span>" \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_surface \
            "\" rise=\"-14000\">​</span>" \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_surface \
            "\" weight=\"bold\">" name "  </span>"
        }
        else {
            out = out \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_primary \
            "\" rise=\"4000\" size=\"xx-large\">▪</span>" \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_surface \
            "\" rise=\"-14000\">​</span>" \
            "<span background=\"" on_primary \
            "\" foreground=\"" on_surface \
            "\" weight=\"bold\">" name "  </span>"
        }
    }

    END {
        print out
    }'
}
# --- 初始渲染 ---
last=""
current=$(render)

printf '%s\n' "$current" > "$CACHE"
last="$current"

sleep 0.5
pkill -RTMIN+15 waybar 2>/dev/null

# --- 监听 workspace 变化 ---
mmsg watch all-tags | while read -r _; do
    pgrep waybar >/dev/null || exit 0

    current=$(render)

    if [[ "$current" != "$last" ]]; then
        printf '%s\n' "$current" > "$CACHE"
        pkill -RTMIN+15 waybar 2>/dev/null
        last="$current"
    fi
done
