#!/bin/bash

LOCKFILE="/tmp/mango-workspace.lock"
CACHE="$HOME/.cache/mango-workspace.log"

exec 200>"$LOCKFILE"

flock -n 200 || exit 1

clean_up() {
    rm -rf $LOCKFILE
    rm -rf $CACHE
}

COLORS="$HOME/.config/waybar/mango/colors.css"

get_color() {
    grep "@define-color $1 " "$COLORS" | awk '{print $3}' | tr -d ';'
}

PRIMARY=$(get_color primary)
ON_PRIMARY=$(get_color on_primary)
ON_SURFACE=$(get_color on_surface)

render() {
    mmsg -g -t 2>/dev/null | grep -E -o "tag [0-9] [0-9] [0-9] [0-9]" | awk \
    -v primary="$PRIMARY" \
    -v on_primary="$ON_PRIMARY" \
    -v on_surface="$ON_SURFACE" '
    BEGIN {
        out = ""
    }

    {
        name     = $2
        focused  = $3
        occupied = $4

        # focused + occupied
        if (focused == 1 && occupied >= 1) {
out = out \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" rise=\"9000\">▪</span>" \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" rise=\"-9000\"> </span>" \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" weight=\"bold\">" name " </span>"
        }

        # focused + empty
        else if (focused == 1 && occupied == 0) {
out = out \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" rise=\"9000\"> </span>" \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" rise=\"-9000\"> </span>" \
    "<span background=\"" primary \
    "\" foreground=\"" on_primary \
    "\" weight=\"bold\">" name " </span>"
        }

        # unfocused + occupied
        else if (focused == 0 && occupied >= 1) {
out = out \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" rise=\"9000\">▫</span>" \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" rise=\"-9000\"> </span>" \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" weight=\"bold\">" name " </span>"
        }

        # unfocused + empty
        else {
out = out \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" rise=\"9000\"> </span>" \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" rise=\"-9000\"> </span>" \
    "<span background=\"" on_primary \
    "\" foreground=\"" on_surface \
    "\" weight=\"bold\">" name " </span>"
        }
    }

    END {
        print out
        fflush()
    }'
}

last=""

echo $(render) > $CACHE

trap clean_up EXIT INT TERM

mmsg -w -t | while read -r _; do
    pgrep waybar || exit 1
    current=$(render)

    if [[ "$current" != "$last" ]]; then
        echo $current  > $CACHE
        pkill -RTMIN+15 waybar
        last="$current"
    fi
done
