#!/usr/bin/env bash

menu="$HOME/.local/bin/wmenu-color"

layouts=(
    tile scroller grid monocle deck fair center_tile right_tile vertical_scroller vertical_tile vertical_grid vertical_deck vertical_fair dwindle
)

layout=$(
    printf '%s\n' "${layouts[@]}" |
    sort |
    $menu -l 6 -p "Layout "
)

[ -z "$layout" ] && exit 0

mmsg dispatch setlayout,$layout
dunstify "Layout: $layout" -h string:x-dunst-stack-tag:layout
