#!/usr/bin/bash

read width<<< $(mmsg get focusing-client | jq '.width')
read height <<< $(mmsg get focusing-client | jq '.height')
width=${width%.*}
height=${height%.*}
read screen_width screen_height <<< $(
    wlr-randr | grep -m1 "current" | awk '{print $1}' | tr 'x' ' '
)
scale=$(wlr-randr | grep "Scale" | cut -d " " -f 4)
screen_width=$(awk "BEGIN {print int($screen_width / $scale)}")
screen_height=$(awk "BEGIN {print int($screen_height / $scale)}")

case "${1:-}" in
    "topleft")
        pos_x=0
        pos_y=23
        ;;
    "topright")
        pos_x=$(($screen_width - $width))
        pos_y=23
        ;;
    "bottomleft")
        pos_x=0
        pos_y=$(($screen_height - $height))
        ;;
    "bottomright")
        pos_x=$(($screen_width - $width))
        pos_y=$(($screen_height - $height))
        ;;
    *)
        exit 1
        ;;
esac

mmsg dispatch movewin,$pos_x,$pos_y
