plugins:
  - fetchart
  - musicbrainz
  - scrub
  - info

import:
  move: yes

musicbrainz:
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1.0
    extra_tags: []
    genres: no
    genres_tag: genre
    external_ids:
        discogs: no
        bandcamp: no
        spotify: no
        deezer: no
        beatport: no
        tidal: no
    data_source_mismatch_penalty: 0.5
    search_limit: 5
