#!/usr/bin/sh
set -eu

# Function: Launches wmenu with a custom color scheme and font.
# Sources color settings from ~/.config/wmenu/color.sh

. "$HOME/.config/wmenu/color.sh"

pgrep -x wmenu > /dev/null && exit 1 ||
timeout 10 wmenu -i \
  -F \
  -E "SourceCodePro regular 13" \
  -C "LXGW WenKai Mono 1" \
  -N "$colorbg" \
  -S "$colorsbg" \
  -s "$colorbg" \
  -M "$colorsbg" \
  -m "$colorbg" \
  "$@"
