#!/usr/bin/bash
set -eu

MENU="$HOME/.local/bin/wmenu-color"

SELECTION=$(printf "Lock\nSuspend\nReboot\nShutdown" | "$MENU" -l4 -i -p "Niri ") || exit 0

case "$SELECTION" in
    "Lock")
        hyprlock ;;
    "Suspend")
        systemctl suspend
        hyprlock
        ;;
    "Reboot")
        systemctl reboot ;;
    "Shutdown")
        systemctl poweroff ;;
esac
