#!/usr/bin/sh
set -eu

MENU="$HOME/.local/bin/wmenu-color"
MUSIC_DIR="$HOME/Music"

controls=$(printf "!clear\n!delete\n!next\n!prev\n!toggle\n!stop\n!all")
music=$(fd -e mp3 -e flac -e m4a -e wav -e ogg --search-path "$MUSIC_DIR" -p -t f | sort | sed "s|^$MUSIC_DIR/||")
option=$(printf "%s\n%s" "$music" "$controls" | "$MENU" -l10 -p "Music ") || exit 0

case "$option" in
  "!clear")
    mpc clear
    exit 0
    ;;
  "!delete")
    cur_position=$(mpc current --format "%position%")
    mpc del $cur_position
    exit 0
    ;;
  "!next")
    mpc next
    exit 0
    ;;
  "!prev")
    mpc prev
    exit 0
    ;;
  "!toggle")
    mpc toggle
    exit 0
    ;;
  "!stop")
    mpc stop
    exit 0
    ;;
  "!all")
    mpc listall | mpc add && mpc shuffle && mpc play >/dev/null && $HOME/.local/bin/notify
    exit 0
    ;;
  *)
    position=$(mpc playlist -f "%position% %file%" | grep -F "$option" | awk '{print $1}')
    list_count=$(mpc playlist | wc -l)
    if [ -n "$position" ]; then
      mpc play "$position" >/dev/null && $HOME/.local/bin/notify
    else
      if [ "$list_count" -eq 0 ]; then
        mpc add "$option" && mpc play >/dev/null && $HOME/.local/bin/notify
      else
        mpc insert "$option" && mpc next >/dev/null && mpc play >/dev/null && $HOME/.local/bin/notify
      fi
    fi
    ;;
esac


