#!/usr/bin/bash
set -eu

MENU="$HOME/.local/bin/wmenu-color"
VID_DIR="$HOME/Videos"

file=$(fd -e mp4 -p -t f --search-path "$VID_DIR" | sort | sed "s|^$VID_DIR/||" | "$MENU" -p "Video " -l10) || exit 0

mpv "$VID_DIR/$file"
