#!/usr/bin/bash
set -eu

. "$HOME/.config/wmenu/color.sh"

pgrep -x wmenu-run > /dev/null && exit 1 ||
timeout 20 wmenu-run -i \
  -F \
  -E "SarasaTermSCNerd 14" \
  -C "LXGWWenKaiMono Nerd Font 14" \
  -l 10 \
  -N "$colorbg" \
  -S "$colorsbg" \
  -s "$colorbg" \
  -M "$colorsbg" \
  -m "$colorbg" \
  -p "Run " \
  "$@"
