#!/usr/bin/env bash

set -euo pipefail

PROFILE="$HOME/.config/mozilla/firefox/k5rd3x5y.default-release"

TMP="$(mktemp -d)"

cp "$PROFILE"/places.sqlite* "$TMP"/

MENU="$HOME/.local/bin/wmenu-color"

choice=$(
sqlite3 -separator '|' "$TMP/places.sqlite" "
SELECT
    COALESCE(parent.title, 'Bookmarks'),
    COALESCE(bookmarks.title, '[No Title]'),
    places.url
FROM moz_bookmarks bookmarks
JOIN moz_places places
    ON bookmarks.fk = places.id
LEFT JOIN moz_bookmarks parent
    ON bookmarks.parent = parent.id
WHERE places.url IS NOT NULL
ORDER BY places.frecency DESC;
" | "$MENU" -p "Bookmarks" -l 20
)

rm -rf "$TMP"

[[ -z "$choice" ]] && exit 0

IFS='|' read -r _ _ url <<< "$choice"

exec firefox "$url"
