#!/usr/bin/env bash
set -eu

TOML_PATH="${HOME}/.config/games"
BIN_PATH="${TOML_PATH}/bin"

WINE_PREFIX="${HOME}/.wine"
PROTON="${HOME}/.local/share/Steam/compatibilitytools.d/GE-Proton10-34"

STORE="steam"

die() {
  printf "Error: %s\n" "$*" >&2
  exit 1
}

ensure_dirs() {
  mkdir -p "$TOML_PATH" "$BIN_PATH"
}

usage() {
  cat <<EOF
Usage:
  game <name> <id> <exe_path>     Add game
  game add <name> <id> <exe_path> Add game
  game delete                     Delete game
  game ls                         Show games
  game run                        Run games
EOF
}

make_toml() {
  name="$1"
  id="$2"
  exe="$3"

  file="${TOML_PATH}/${name}.toml"

  cat > "$file" <<EOF
[umu]
prefix = "${WINE_PREFIX}"
proton = "${PROTON}"
game_id = "umu-${id}"
exe = "$(realpath "$exe")"
launch_args = []
store = "${STORE}"
EOF
}

make_bin() {
  name="$1"
  exe="$2"

  file="${BIN_PATH}/${name}"

  game_dir="$(dirname "$(realpath "$exe")")"

  cat > "$file" <<EOF
#!/usr/bin/env sh
set -eu

cd "${game_dir}"

exec gamescope -f -W 3840 -H 2160 -r 60 -- \
  umu-run --config "${TOML_PATH}/${name}.toml"
EOF

  chmod +x "$file"

  "${HOME}/.local/bin/lnk" "$file"
}

add_game() {
  [ $# -eq 3 ] || die "add_game requires: name id exe_path"

  name="$1"
  id="$2"
  exe="$3"

  [ -f "$exe" ] || die "exe not found: $exe"

  ensure_dirs

  make_toml "$name" "$id" "$exe"
  make_bin "$name" "$exe"

  printf "Added game: %s (id=%s)\n" "$name" "$id"
}

get_id_from_toml() {
  name="$1"
  file="${TOML_PATH}/${name}.toml"

  [ -f "$file" ] || die "toml not found: $file"

  sed -n 's/^game_id = "umu-\(.*\)"/\1/p' "$file"
}

list_games() {
  [ -d "$BIN_PATH" ] || return 0

  fd . "$BIN_PATH" \
    --max-depth 1 \
    -t f \
    --exec basename {} \;
}

delete_game() {
  name=$(list_games | sort | fzf) || exit 1

  toml="${TOML_PATH}/${name}.toml"
  bin="${BIN_PATH}/${name}"
  link="${HOME}/.local/bin/${name}"

  id="$(get_id_from_toml "$name")"

  rm -f "$toml" "$bin" "$link"

  printf "Deleted game: %s (id=%s)\n" "$name" "$id"
}

run_game() {
  [ -d "$BIN_PATH" ] || die "no games found"

  select=$(
    list_games | sort |
      "${HOME}/.local/bin/wmenu-color" -l 6 -p "Game "
  ) || exit 1

  game_exe_path="${BIN_PATH}/${select}"

  if [ -x "$game_exe_path" ]; then
    exec "$game_exe_path"
  else
    die "game launcher not executable: $game_exe_path"
  fi
}

main() {
  case "${1:-}" in
    a|add|-a)
      shift
      [ $# -eq 3 ] || {
        usage
        exit 1
      }

      add_game "$@"
      ;;

    l|ls|-l)
      list_games
      ;;

    d|delete|-d)
      shift
      delete_game "$@"
      ;;

    r|run|-r)
      run_game
      ;;

    ""|help|-h|--help)
      usage
      ;;

    *)
      [ $# -eq 3 ] || {
        usage
        exit 1
      }

      add_game "$@"
      ;;
  esac
}

main "$@"
