#!/usr/bin/bash

set -euo pipefail

$HOME/.local/bin/cache-img

# WALLPAPER="$HOME/Pictures/Wallpapers"
WALLPAPER="$HOME/.cache/wallpaper_thumbs"

mode="$(gsettings get org.gnome.desktop.interface color-scheme)"
if [ "$mode" = "'prefer-light'" ]; then
    CUR_WALLMODE="Light"
else
    CUR_WALLMODE="Dark"
fi

CUR_WALLPATH="$WALLPAPER/$CUR_WALLMODE"

[[ -n "$CUR_WALLPATH" ]] || exit 1
pgrep -x swayimg >/dev/null 2>&1 || /usr/bin/swayimg -g --class="wallpaper_selector" --size=640,360 "$CUR_WALLPATH"
