#!/usr/bin/sh
# swayimg script to rotate image with input degree via wmenu
# Shift+r = exec ~/.local/bin/swayimg-rotate "%"; reload
set -eu

[ $# -ge 1 ] || exit 1
target=$1
target_name=$(basename "$target")
short_name=$(printf '%s\n' "$target_name" |
  awk '{if(length($0) > 80) print substr($0, 1, 35) "..." substr($0, length($0)-34, 35); else print $0}')

user_input=$(wmenu-color -p "[$(basename "$0")] Rotate degree: $short_name ")

if [ -n "$user_input" ]; then
  tmp_output=$(mktemp "${target}.XXXXXX")
  convert "$target" -rotate "$user_input" "$tmp_output"
  mv -- "$tmp_output" "$target"
  pkill -SIGUSR1 swayimg
  notify-send -t 1101 -u low -r 3301 "swayimg" "$target_name is rotated"
else
  exit 1
fi
