#!/usr/bin/bash

set -euo pipefail

WALLPAPER="$HOME/Pictures/Wallpapers"
CUR_WALLMODE=$(awww query | grep -Eo "Dark|Light")
CUR_WALLPATH="$WALLPAPER/$CUR_WALLMODE"

[[ -n "$CUR_WALLPATH" ]] || exit 1
pgrep -x swayimg >/dev/null 2>&1 || /usr/bin/swayimg -g --class="wallpaper_selector" --size=640,360 "$CUR_WALLPATH"
