#!/usr/bin/bash

TARGET_FILE="/tmp/my_timer_target"
[[ -f $TARGET_FILE ]] || exit 0
COLORS="$HOME/.config/waybar/mango/colors.css"

get_color() {
    grep "@define-color $1 " "$COLORS" | awk '{print $3}' | tr -d ';'
}

ERROR="$(get_color error)"
ERROR="${ERROR:-#ff0000}"

seconds_to_fmt() {
    local total=$1

    local h=$(( total / 3600 ))
    local m=$(( (total % 3600) / 60 ))
    local s=$(( total % 60 ))

    if (( h > 0 )); then
        printf "%dh:%02dm:%02ds\n" "$h" "$m" "$s"
    elif (( m > 0 )); then
        printf "%dm:%02ds\n" "$m" "$s"
    else
        printf "%ds\n" "$s"
    fi
}

if [ ! -f "$TARGET_FILE" ]; then
    echo ""
    return
fi

target=$(cat "$TARGET_FILE")
now=$(date +%s)
rem=$(( target - now ))

if [ "$rem" -le 0 ]; then
    echo "<span foreground=\"$ERROR\">󱫌  Done</span>"

else
    echo "󱎫 $(seconds_to_fmt $rem)"
fi
