rootcolor=0xf2ecbcff
maximizescreencolor=0xf2ecbcff
urgentcolor=0xf2ecbcff
scratchpadcolor=0xf2ecbcff
overlaycolor=0xf2ecbcff
bordercolor=0xf2ecbcff
dropcolor=0xf2ecbcff

focuscolor=0x6f894eff

globalcolor=0xc84053ff
