exec-once=dunst

exec-once=wl-paste --watch cliphist store

exec-once=fcitx5 -d

exec-once=/usr/bin/clash-verge

exec-once=~/.local/bin/foots

exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/bin/xhost +si:localuser:root

exec-once=~/.local/bin/remove-thunderbird

exec-once=awww-daemon
exec-once=~/.local/bin/set_wallpaper

exec-once=echo 0411 | sudo -S ~/.local/bin/bind-monitor

exec-once=~/.local/bin/waybar-switch mango

exec-once=pgrep xremap || echo 0411 | sudo -E -S xremap --watch=config,device ~/.config/xremap/config.yml
