# set terminal to swallow
windowrule=isterm:1,appid:footclient

# flooating window
windowrule=isfloating:1,width:1706,height:940,appid:^org\.gnome\.Nautilus$
windowrule=isfloating:1,width:1706,height:940,appid:com.gabm.satty
windowrule=isfloating:1,width:1706,height:940,appid:swayimg
windowrule=isfloating:1,width:1706,height:940,appid:spotify
windowrule=isfloating:1,width:1706,height:940,appid:wallpaper_selector
windowrule=isfloating:1,width:1706,height:940,appid:localsend
windowrule=isfloating:1,width:1706,height:940,appid:floatterm
windowrule=isfloating:1,width:1706,height:940,appid:satty
windowrule=isfloating:1,width:1706,height:940,appid:clash-verge
windowrule=isfloating:1,width:1706,height:940,appid:btrfs-assistant
windowrule=isfloating:1,width:1706,height:940,title:.*足迹.*,appid:firefox
windowrule=isfloating:1,width:1706,height:940,appid:mpv

# scratchpad
windowrule=isnamedscratchpad:1,width:1706,height:940,appid:floatterm
