# set terminal to swallow
windowrule=isterm:1,appid:footclient

# flooating window
windowrule=width:1500,height:1500,appid:footclient
windowrule=isfloating:1,appid=org.gnome.Nautilus
windowrule=isfloating:1,appid=com.gabm.satty
windowrule=isfloating:1,appid=swayimg
windowrule=isfloating:1,appid=spotify
windowrule=isfloating:1,appid=wallpaper_selector
windowrule=isfloating:1,appid=localsend
windowrule=isfloating:1,appid=floatterm
windowrule=isfloating:1,appid=satty
windowrule=isfloating:1,appid=clash-verge
windowrule=isfloating:1,appid=btrfs-assistant
windowrule=isfloating:1,title=.*足迹.*,appid=firefox
