# set terminal to swallow
windowrule=isterm:1,appid:footclient

# flooating window
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:^org\.gnome\.Nautilus$
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:com.gabm.satty
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:swayimg
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:spotify
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:wallpaper_selector
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:localsend
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:floatterm
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:satty
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:clash-verge
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:btrfs-assistant
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,title:.*足迹.*,appid:firefox
windowrule=isfloating:1,width:1706,height:960,offsetx:0,offsety:0,appid:mpv
