#!/usr/bin/sh

for color in "$@"; do
    red="$(echo "$color" | cut -c1-2)"
    grn="$(echo "$color" | cut -c3-4)"
    blu="$(echo "$color" | cut -c5-6)"

    printf "%d,%d,%d\n" "0x$red" "0x$grn" "0x$blu"
done
