#!/usr/bin/sh

# mu: print human-readable memory usage by process name
# Usage: mu [OPTION]... [PROCESS NAME]...
#    -h, --help          print this message

columns=$(tput cols)
cmd_length=$((columns / 2))

[ -z "$1" ] && \
    ps axh -o rss,pid,cmd:20 --sort=-rss \
        | awk '{printf "%s %.'"$cmd_length"'s %.2f MB\n", $2, $3, $1/1024}' \
        | head -20 \
        | column -t \
    || ps -o rss,pid,cmd -p $(pidof -x "$@") \
        | awk 'NR==1 {next} {printf "%s %.'"$cmd_length"'s %.2f MB\n", $2, $3, $1/1024}' \
        | column -t
