#!/usr/bin/bash
set -euo pipefail

tmp=$(mktemp --suffix=.png)
trap 'rm -f "$tmp"' EXIT

grim -g "$(slurp)" "$tmp"

# 原图尝试识别
result=$(zbarimg --raw "$tmp" 2>/dev/null || true)

# 失败则反色后重试
if [[ -z "$result" ]]; then
    magick "$tmp" -negate "$tmp"

    result=$(zbarimg --raw "$tmp" 2>/dev/null || true)
fi

result=$(printf '%s' "$result" | tr -d '\r\n')

# 保存二维码内容到剪贴板
if [[ -n "$result" ]]; then
    case "$XDG_CURRENT_DESKTOP" in
        "niri")
            exit 0
            ;;
        "mango")
            current_app=$(mmsg get focusing-client | jq -r '.appid')
            ;;
        *)
            exit 0
            ;;
    esac

    if [[ "$current_app" == "firefox" ]]; then
        firefox ${result}
    else
        printf '%s' "$result" | wl-copy
    fi
fi
