#!/usr/bin/bash

# qrdecode: decode screenshot qrcode
niri msg action screenshot &
event=$(timeout 30 niri msg event-stream | grep -m 1 "Screenshot captured")
if [[ -n "$event" ]]; then
  wl-paste | zbarimg --raw - | tr -d '\r\n' | wl-copy
  current_app=$(niri msg --json focused-window | jq -r '.app_id')
  if [[ "$current_app" = "firefox" ]]; then
    wtype p
  fi
else
  exit 1
fi
