#!/usr/bin/bash

niri msg action do-screen-transition --delay-ms 800 &
CONFIG_FILE="$HOME/.config/noctalia/settings.json"

DARK_WALLPAPER="/home/harunato/Pictures/Wallpapers/Dark"
LIGHT_WALLPAPER="/home/harunato/Pictures/Wallpapers/Light"
mode="$(gsettings get org.gnome.desktop.interface color-scheme)"

if [ "$mode" = "'prefer-light'" ]; then
  TARGET_WALLPAPER_PATH="$DARK_WALLPAPER"
  GTK_MODE="prefer-dark"
  GTK_THEME="adw-gtk3-dark"
  SIGNAL="-USR1"
  MATUGEN_COLOR="dark"
else
  TARGET_WALLPAPER_PATH="$LIGHT_WALLPAPER"
  GTK_MODE="prefer-light"
  GTK_THEME="adw-gtk3"
  SIGNAL="-USR2"
  MATUGEN_COLOR="light"
fi

kill "$SIGNAL" $(pgrep -f "foot --server")
matugen json "/home/harunato/.config/matugen/colors/kanagawa/$MATUGEN_COLOR.json" -m $MATUGEN_COLOR
gsettings set org.gnome.desktop.interface color-scheme "$GTK_MODE"
gsettings set org.gnome.desktop.interface gtk-theme ""
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
