swayimg.slideshow.set_window_background("mirror")
-- swayimg.slideshow.set_image_background("#000000ff")
swayimg.slideshow.set_default_scale("optimal")
swayimg.slideshow.set_default_position("center")
swayimg.slideshow.set_timeout(3)

swayimg.slideshow.set_text("topleft", { "{name}  {format}  {sizehr}  {frame.width}x{frame.height}  {meta.*}" })
swayimg.slideshow.set_text("topright", { "{list.index}/{list.total}" })
swayimg.slideshow.set_text("bottomleft", { "{scale}%  {frame.index}/{frame.total}" })
swayimg.slideshow.set_text("bottomright", { "{dir}" }) -- status 属性在当前版本暂无直接对应的模板字段

swayimg.slideshow.bind_reset()
swayimg.slideshow.on_key("Return", function()
	swayimg.set_mode("gallery")
end)
swayimg.slideshow.on_key("s", function()
	swayimg.set_mode("viewer")
end)
swayimg.slideshow.on_key("q", function()
	swayimg.exit()
end)
swayimg.slideshow.on_key("n", function()
	swayimg.slideshow.switch_image("next")
end)
swayimg.slideshow.on_key("p", function()
	swayimg.slideshow.switch_image("prev")
end)
swayimg.slideshow.on_key("Shift-n", function()
	swayimg.slideshow.switch_image("next_dir")
end)
swayimg.slideshow.on_key("Shift-p", function()
	swayimg.slideshow.switch_image("prev_dir")
end)
swayimg.slideshow.on_key("g", function()
	swayimg.slideshow.switch_image("first")
end)
swayimg.slideshow.on_key("Shift-g", function()
	swayimg.slideshow.switch_image("last")
end)
swayimg.slideshow.on_key("m", function()
	if swayimg.text.visible() then
		swayimg.text.hide()
	else
		swayimg.text.show()
	end
end)
