source-file $HOME/.config/tmux/color.conf

set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -s escape-time 0
set -g status-right '#{pane_title}'
set -g set-titles on
set -g set-titles-string "#T"
set -g allow-rename off

# Intuitive split commands
bind-key C-\\ split-window -h
bind-key C-\' split-window -v

bind-key r source-file ~/.config/tmux/tumx.conf
