#
# ~/.bashrc
#

export HISTFILE="$HOME/.config/bash/bash_history"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# custom
source $HOME/.config/fish/alias.sh
eval "$(zoxide init bash)"
eval "$(starship init bash)"
eval "$(fzf --bash)"
